name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Kết nối ssh linux -> và pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /var/www/project5/client_md5
          echo "GitPull dữ liệu mới"
          git pull
          git status
          echo "kiểm tra và kích hoạt nvm"
          . $HOME/.nvm/nvm.sh
          nvm use
          echo "tạo và cấu hình .env"
          cp .env.example .env
          echo "cài đặt nodemodules"
          npm ci
          echo "build dự án"
          npm run build
          echo "thông báo"
          curl -X POST -H "Content-Type: application/json" -H "Authorization: ${{ secrets.DISCORD_TOKEN }}" -d '{"content":"Dự án React đã deploy thành công link: https://nks.io.vn "}' ${{ secrets.DISCORD_URL }}
